services:
  - type: web
    name: react-ssr-ssg-test
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production